# Generated by Django 3.0.1 on 2020-01-01 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dev_tool', '0002_auto_20191231_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmanhistory',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='port',
            field=models.IntegerField(default=22),
        ),
    ]
