# Generated by Django 3.0.1 on 2020-01-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_tool', '0003_auto_20200101_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='alias',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
